package tools

import (
	"fmt"

	"github.com/frozenkro/mcpsequencer/internal/globals"
	"github.com/mark3labs/mcp-go/mcp"
)

var CreateProjectTool = mcp.NewTool("createProject",
	mcp.WithDescription("Create a new LLM-driven project (collection of small tasks)"),
	mcp.WithString(string(globals.ProjectName),
		mcp.Required(),
		mcp.Description("Name of the new project"),
	),
	mcp.WithString(string(globals.ProjectDesc),
		mcp.Required(),
		mcp.Description("Description of the new project, will be used to provide global context to agents performing individual tasks."),
	),
	mcp.WithString(string(globals.ProjectDir),
		mcp.Description("Absolute path to the working directory of this project on the machine. Provide this up front if planning a feature for an existing project."),
	),
	mcp.WithString("Tasks",
		mcp.Required(),
		mcp.Description("Json array that follows specific schema and rules. Make an mcp call to the getTaskListInstructions tool for instructions."),
	),
)

var UpdateProjectTool = mcp.NewTool("updateProject",
	mcp.WithDescription("Update an LLM-driven project"),
	mcp.WithNumber(string(globals.ProjectId),
		mcp.Required(),
		mcp.Description(fmt.Sprintf("%v of project to update", globals.ProjectId)),
	),
	mcp.WithString(string(globals.ProjectName),
		mcp.Required(),
		mcp.Description("Project name"),
	),
	mcp.WithString(string(globals.ProjectDesc),
		mcp.Required(),
		mcp.Description("Description of the project, will be used to provide global context to agents performing individual tasks."),
	),
	mcp.WithString(string(globals.ProjectDir),
		mcp.Description("Absolute path to the working directory of this project on the machine."),
	),
)

var DeleteProjectTool = mcp.NewTool("deleteProject",
	mcp.WithDescription("Delete an LLM-driven project"),
	mcp.WithNumber(string(globals.ProjectId),
		mcp.Required(),
		mcp.Description(fmt.Sprintf("%v of project to delete", globals.ProjectId)),
	),
)

var AddTaskTool = mcp.NewTool("addTask",
	mcp.WithDescription("Add new task to an LLM-driven project"),
	mcp.WithNumber(string(globals.ProjectId),
		mcp.Required(),
		mcp.Description("ID of Project to add task to"),
	),
	mcp.WithString(string(globals.TaskName),
		mcp.Required(),
		mcp.Description("Name of the task"),
	),
	mcp.WithString(string(globals.Description),
		mcp.Required(),
		mcp.Description("Detailed description of the task"),
	),
	mcp.WithNumber(string(globals.SortId),
		mcp.Required(),
		mcp.Description("Sort order of new task. 0 for first, -1 for last"),
	),
	mcp.WithArray(string(globals.Dependencies),
		mcp.Description("The taskIds (NOT sortIds) of any tasks that must be completed before this task. Tasks are otherwise assumed to be parallelizable."),
	),
)

var BeginTaskTool = mcp.NewTool("beginTask",
	mcp.WithDescription("Indicate that a task is in-progress"),
	mcp.WithNumber(string(globals.TaskId),
		mcp.Required(),
		mcp.Description(fmt.Sprintf("%v of task (NOT the %v)", globals.TaskId, globals.SortId)),
	),
)

var CompleteTaskTool = mcp.NewTool("completeTask",
	mcp.WithDescription("Indicate that a task is completed"),
	mcp.WithNumber(string(globals.TaskId),
		mcp.Required(),
		mcp.Description(fmt.Sprintf("%v of task (NOT the %v)", globals.TaskId, globals.SortId)),
	),
)

var GetProjectsTool = mcp.NewTool("getAllProjects",
	mcp.WithDescription("Get a list of all project names and IDs"),
)

var GetTasksTool = mcp.NewTool("getTasksForProject",
	mcp.WithDescription("Get all tasks for a project"),
	mcp.WithNumber(string(globals.ProjectId),
		mcp.Required(),
		mcp.Description("ID of project"),
	),
)

var GetTaskListInstructionsTool = mcp.NewTool("getTaskListInstructions",
	mcp.WithDescription("Get instructions on how tasks are defined and organized"),
)

var CreatePhaseTool = mcp.NewTool("createPhase",
	mcp.WithDescription("Create a new phase in a project"),
	mcp.WithNumber(string(globals.ProjectId),
		mcp.Required(),
		mcp.Description("ID of the project"),
	),
	mcp.WithString(string(globals.PhaseName),
		mcp.Required(),
		mcp.Description("Name of the phase"),
	),
	mcp.WithString(string(globals.Description),
		mcp.Description("Description of the phase"),
	),
	mcp.WithString(string(globals.StartDate),
		mcp.Description("Start date of the phase (YYYY-MM-DD)"),
	),
	mcp.WithString(string(globals.EndDate),
		mcp.Description("End date of the phase (YYYY-MM-DD)"),
	),
	mcp.WithNumber(string(globals.SortId),
		mcp.Required(),
		mcp.Description("Sort order of the phase"),
	),
)

var GetPhasesTool = mcp.NewTool("getPhasesForProject",
	mcp.WithDescription("Get all phases for a project"),
	mcp.WithNumber(string(globals.ProjectId),
		mcp.Required(),
		mcp.Description("ID of the project"),
	),
)

var UpdatePhaseTool = mcp.NewTool("updatePhase",
	mcp.WithDescription("Update an existing phase"),
	mcp.WithNumber(string(globals.PhaseId),
		mcp.Required(),
		mcp.Description("ID of the phase to update"),
	),
	mcp.WithString(string(globals.PhaseName),
		mcp.Required(),
		mcp.Description("Name of the phase"),
	),
	mcp.WithString(string(globals.Description),
		mcp.Description("Description of the phase"),
	),
	mcp.WithString(string(globals.StartDate),
		mcp.Description("Start date of the phase (YYYY-MM-DD)"),
	),
	mcp.WithString(string(globals.EndDate),
		mcp.Description("End date of the phase (YYYY-MM-DD)"),
	),
	mcp.WithNumber(string(globals.SortId),
		mcp.Required(),
		mcp.Description("Sort order of the phase"),
	),
)

var DeletePhaseTool = mcp.NewTool("deletePhase",
	mcp.WithDescription("Delete a phase"),
	mcp.WithNumber(string(globals.PhaseId),
		mcp.Required(),
		mcp.Description("ID of the phase to delete"),
	),
)

var SetTaskOwnerTool = mcp.NewTool("setTaskOwner",
	mcp.WithDescription("Set the owner of a task"),
	mcp.WithNumber(string(globals.TaskId),
		mcp.Required(),
		mcp.Description("ID of the task"),
	),
	mcp.WithString(string(globals.Owner),
		mcp.Required(),
		mcp.Description("Owner of the task: USER, AI_AGENT, or COLLAB"),
	),
)

var SetTaskScheduleTool = mcp.NewTool("setTaskSchedule",
	mcp.WithDescription("Set the schedule for a task"),
	mcp.WithNumber(string(globals.TaskId),
		mcp.Required(),
		mcp.Description("ID of the task"),
	),
	mcp.WithString(string(globals.ScheduledDate),
		mcp.Description("Scheduled date for the task (YYYY-MM-DD)"),
	),
	mcp.WithNumber(string(globals.PhaseId),
		mcp.Description("ID of the phase to assign the task to"),
	),
)

var SetTaskBlockerTool = mcp.NewTool("setTaskBlocker",
	mcp.WithDescription("Set a blocker on a task"),
	mcp.WithNumber(string(globals.TaskId),
		mcp.Required(),
		mcp.Description("ID of the task"),
	),
	mcp.WithString(string(globals.BlockerText),
		mcp.Required(),
		mcp.Description("Description of the blocker"),
	),
)

var ResolveTaskBlockerTool = mcp.NewTool("resolveTaskBlocker",
	mcp.WithDescription("Resolve the blocker on a task"),
	mcp.WithNumber(string(globals.TaskId),
		mcp.Required(),
		mcp.Description("ID of the task"),
	),
)

var AddTaskNoteTool = mcp.NewTool("addTaskNote",
	mcp.WithDescription("Add a note to a task"),
	mcp.WithNumber(string(globals.TaskId),
		mcp.Required(),
		mcp.Description("ID of the task"),
	),
	mcp.WithString(string(globals.Note),
		mcp.Required(),
		mcp.Description("Note text"),
	),
)

var GetTaskNotesTool = mcp.NewTool("getTaskNotes",
	mcp.WithDescription("Get all notes for a task"),
	mcp.WithNumber(string(globals.TaskId),
		mcp.Required(),
		mcp.Description("ID of the task"),
	),
)

var GetTodaysTasksTool = mcp.NewTool("getTodaysTasks",
	mcp.WithDescription("Get tasks scheduled for today"),
	mcp.WithNumber(string(globals.ProjectId),
		mcp.Required(),
		mcp.Description("ID of the project"),
	),
)

var GetTasksByOwnerTool = mcp.NewTool("getTasksByOwner",
	mcp.WithDescription("Get tasks by owner for a project"),
	mcp.WithNumber(string(globals.ProjectId),
		mcp.Required(),
		mcp.Description("ID of the project"),
	),
	mcp.WithString(string(globals.Owner),
		mcp.Required(),
		mcp.Description("Owner: USER, AI_AGENT, or COLLAB"),
	),
)

var AddExitCriterionTool = mcp.NewTool("addExitCriterion",
	mcp.WithDescription("Add an exit criterion to a phase"),
	mcp.WithNumber(string(globals.PhaseId),
		mcp.Required(),
		mcp.Description("ID of the phase"),
	),
	mcp.WithString(string(globals.Description),
		mcp.Required(),
		mcp.Description("Description of the exit criterion"),
	),
	mcp.WithNumber(string(globals.SortId),
		mcp.Required(),
		mcp.Description("Sort order of the exit criterion"),
	),
)

var CompleteExitCriterionTool = mcp.NewTool("completeExitCriterion",
	mcp.WithDescription("Mark an exit criterion as complete"),
	mcp.WithNumber(string(globals.CriterionId),
		mcp.Required(),
		mcp.Description("ID of the exit criterion"),
	),
)

var GetExitCriteriaTool = mcp.NewTool("getExitCriteriaForPhase",
	mcp.WithDescription("Get all exit criteria for a phase"),
	mcp.WithNumber(string(globals.PhaseId),
		mcp.Required(),
		mcp.Description("ID of the phase"),
	),
)

var GetDownstreamTasksTool = mcp.NewTool("getDownstreamTasks",
	mcp.WithDescription("Get downstream tasks (tasks that depend on this task)"),
	mcp.WithNumber(string(globals.TaskId),
		mcp.Required(),
		mcp.Description("ID of the task"),
	),
)

var GetUpstreamTasksTool = mcp.NewTool("getUpstreamTasks",
	mcp.WithDescription("Get upstream tasks (tasks this task depends on)"),
	mcp.WithNumber(string(globals.TaskId),
		mcp.Required(),
		mcp.Description("ID of the task"),
	),
)
