// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package projectsdb

type Project struct {
	ProjectID int64
	Name      string
}

type Task struct {
	TaskID      int64
	Description string
	ProjectID   int64
	Sort        int64
	IsCompleted int64
	IsFailed    int64
	Notes       interface{}
}
