// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package projectsdb

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name)
VALUES (?)
RETURNING project_id, name
`

func (q *Queries) CreateProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, name)
	var i Project
	err := row.Scan(&i.ProjectID, &i.Name)
	return i, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (description, project_id, sort, is_completed, is_failed, notes)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING task_id, description, project_id, sort, is_completed, is_failed, notes
`

type CreateTaskParams struct {
	Description string
	ProjectID   int64
	Sort        int64
	IsCompleted int64
	IsFailed    int64
	Notes       interface{}
}

// Tasks CRUD Operations
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Description,
		arg.ProjectID,
		arg.Sort,
		arg.IsCompleted,
		arg.IsFailed,
		arg.Notes,
	)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Description,
		&i.ProjectID,
		&i.Sort,
		&i.IsCompleted,
		&i.IsFailed,
		&i.Notes,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE project_id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, projectID)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE task_id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, taskID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, taskID)
	return err
}

const deleteTasksByProject = `-- name: DeleteTasksByProject :exec
DELETE FROM tasks
WHERE project_id = ?
`

func (q *Queries) DeleteTasksByProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByProject, projectID)
	return err
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT project_id, name
FROM projects
ORDER BY name
`

func (q *Queries) GetAllProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ProjectID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProjectsWithTaskCounts = `-- name: GetAllProjectsWithTaskCounts :many
SELECT 
    p.project_id,
    p.name,
    COUNT(t.task_id) as task_count,
    COUNT(CASE WHEN t.is_completed = 1 THEN 1 END) as completed_count,
    COUNT(CASE WHEN t.is_failed = 1 THEN 1 END) as failed_count
FROM projects p
LEFT JOIN tasks t ON p.project_id = t.project_id
GROUP BY p.project_id, p.name
ORDER BY p.name
`

type GetAllProjectsWithTaskCountsRow struct {
	ProjectID      int64
	Name           string
	TaskCount      int64
	CompletedCount int64
	FailedCount    int64
}

func (q *Queries) GetAllProjectsWithTaskCounts(ctx context.Context) ([]GetAllProjectsWithTaskCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProjectsWithTaskCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProjectsWithTaskCountsRow
	for rows.Next() {
		var i GetAllProjectsWithTaskCountsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Name,
			&i.TaskCount,
			&i.CompletedCount,
			&i.FailedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTasks = `-- name: GetAllTasks :many
SELECT task_id, description, project_id, sort, is_completed, is_failed, notes
FROM tasks
ORDER BY sort
`

func (q *Queries) GetAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Description,
			&i.ProjectID,
			&i.Sort,
			&i.IsCompleted,
			&i.IsFailed,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedTasks = `-- name: GetCompletedTasks :many
SELECT task_id, description, project_id, sort, is_completed, is_failed, notes
FROM tasks
WHERE is_completed = 1
ORDER BY sort
`

func (q *Queries) GetCompletedTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Description,
			&i.ProjectID,
			&i.Sort,
			&i.IsCompleted,
			&i.IsFailed,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFailedTasks = `-- name: GetFailedTasks :many
SELECT task_id, description, project_id, sort, is_completed, is_failed, notes
FROM tasks
WHERE is_failed = 1
ORDER BY sort
`

func (q *Queries) GetFailedTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getFailedTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Description,
			&i.ProjectID,
			&i.Sort,
			&i.IsCompleted,
			&i.IsFailed,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingTasks = `-- name: GetPendingTasks :many
SELECT task_id, description, project_id, sort, is_completed, is_failed, notes
FROM tasks
WHERE is_completed = 0 AND is_failed = 0
ORDER BY sort
`

func (q *Queries) GetPendingTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getPendingTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Description,
			&i.ProjectID,
			&i.Sort,
			&i.IsCompleted,
			&i.IsFailed,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProject = `-- name: GetProject :one
SELECT project_id, name
FROM projects
WHERE project_id = ?
`

func (q *Queries) GetProject(ctx context.Context, projectID int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, projectID)
	var i Project
	err := row.Scan(&i.ProjectID, &i.Name)
	return i, err
}

const getProjectWithTaskCount = `-- name: GetProjectWithTaskCount :one
SELECT 
    p.project_id,
    p.name,
    COUNT(t.task_id) as task_count,
    COUNT(CASE WHEN t.is_completed = 1 THEN 1 END) as completed_count,
    COUNT(CASE WHEN t.is_failed = 1 THEN 1 END) as failed_count
FROM projects p
LEFT JOIN tasks t ON p.project_id = t.project_id
WHERE p.project_id = ?
GROUP BY p.project_id, p.name
`

type GetProjectWithTaskCountRow struct {
	ProjectID      int64
	Name           string
	TaskCount      int64
	CompletedCount int64
	FailedCount    int64
}

func (q *Queries) GetProjectWithTaskCount(ctx context.Context, projectID int64) (GetProjectWithTaskCountRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectWithTaskCount, projectID)
	var i GetProjectWithTaskCountRow
	err := row.Scan(
		&i.ProjectID,
		&i.Name,
		&i.TaskCount,
		&i.CompletedCount,
		&i.FailedCount,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT task_id, description, project_id, sort, is_completed, is_failed, notes
FROM tasks
WHERE task_id = ?
`

func (q *Queries) GetTask(ctx context.Context, taskID int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, taskID)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Description,
		&i.ProjectID,
		&i.Sort,
		&i.IsCompleted,
		&i.IsFailed,
		&i.Notes,
	)
	return i, err
}

const getTasksByProject = `-- name: GetTasksByProject :many
SELECT task_id, description, project_id, sort, is_completed, is_failed, notes
FROM tasks
WHERE project_id = ?
ORDER BY sort
`

func (q *Queries) GetTasksByProject(ctx context.Context, projectID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Description,
			&i.ProjectID,
			&i.Sort,
			&i.IsCompleted,
			&i.IsFailed,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksWithProject = `-- name: GetTasksWithProject :many

SELECT 
    t.task_id,
    t.description,
    t.project_id,
    t.sort,
    t.is_completed,
    t.is_failed,
    t.notes,
    p.name as project_name
FROM tasks t
JOIN projects p ON t.project_id = p.project_id
ORDER BY p.name, t.sort
`

type GetTasksWithProjectRow struct {
	TaskID      int64
	Description string
	ProjectID   int64
	Sort        int64
	IsCompleted int64
	IsFailed    int64
	Notes       interface{}
	ProjectName string
}

// Joined queries for richer data
func (q *Queries) GetTasksWithProject(ctx context.Context) ([]GetTasksWithProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, getTasksWithProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTasksWithProjectRow
	for rows.Next() {
		var i GetTasksWithProjectRow
		if err := rows.Scan(
			&i.TaskID,
			&i.Description,
			&i.ProjectID,
			&i.Sort,
			&i.IsCompleted,
			&i.IsFailed,
			&i.Notes,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = ?
WHERE project_id = ?
RETURNING project_id, name
`

type UpdateProjectParams struct {
	Name      string
	ProjectID int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Name, arg.ProjectID)
	var i Project
	err := row.Scan(&i.ProjectID, &i.Name)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET description = ?, sort = ?, is_completed = ?, is_failed = ?, notes = ?
WHERE task_id = ?
RETURNING task_id, description, project_id, sort, is_completed, is_failed, notes
`

type UpdateTaskParams struct {
	Description string
	Sort        int64
	IsCompleted int64
	IsFailed    int64
	Notes       interface{}
	TaskID      int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Description,
		arg.Sort,
		arg.IsCompleted,
		arg.IsFailed,
		arg.Notes,
		arg.TaskID,
	)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Description,
		&i.ProjectID,
		&i.Sort,
		&i.IsCompleted,
		&i.IsFailed,
		&i.Notes,
	)
	return i, err
}

const updateTaskSort = `-- name: UpdateTaskSort :exec
UPDATE tasks
SET sort = ?
WHERE task_id = ?
`

type UpdateTaskSortParams struct {
	Sort   int64
	TaskID int64
}

func (q *Queries) UpdateTaskSort(ctx context.Context, arg UpdateTaskSortParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskSort, arg.Sort, arg.TaskID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET is_completed = ?, is_failed = ?
WHERE task_id = ?
RETURNING task_id, description, project_id, sort, is_completed, is_failed, notes
`

type UpdateTaskStatusParams struct {
	IsCompleted int64
	IsFailed    int64
	TaskID      int64
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.IsCompleted, arg.IsFailed, arg.TaskID)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Description,
		&i.ProjectID,
		&i.Sort,
		&i.IsCompleted,
		&i.IsFailed,
		&i.Notes,
	)
	return i, err
}
