// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package projectsdb

type Dependency struct {
	TaskID    int64
	DependsOn int64
}

type Project struct {
	ProjectID    int64
	Name         string
	Description  interface{}
	AbsolutePath interface{}
}

type Task struct {
	TaskID       int64
	Name         string
	Description  string
	ProjectID    int64
	Sort         int64
	IsCompleted  int64
	IsInProgress int64
	Notes        interface{}
}
